burgr-model-version: 1.0.0

services:

  add_item:
    methods:
      execute:
        inputs:
          item: item
    dependencies:
      item:
    api_description:
      is_anonymous: true

  update_item:
    methods:
      execute:
        inputs:
          id:
          name:
          status:
          due_date: datetime
    dependencies:
      item:
    api_description:
      is_anonymous: true

  get_items:
    methods:
      execute:
        result: item[]
    dependencies:
      item:
    api_description:
      is_anonymous: true